HtmlParser/Models/ErrorViewModel.cs
using System;

namespace HtmlParser.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HtmlParser/Models/ImageParseResultsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HtmlParser.Models
{
    public class ImageParseResultsModel
    {
        
            public IEnumerable<string> Images { get; set; }
        
    }
}

HtmlParser/Models/InputModel.cs
using HtmlParser.Enums;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HtmlParser.Models
 {          
    public class InputModel
    {

        [Required(ErrorMessage = "The information to be supplied in this field is mandatory.")]
        [Display(Name = "Site Url")]

        public string Field { get; set; }

        [Display(Name = "Parsing Type")]
        public ParsingTypes? ParsingType { get; set; } 
   

    }

 
}

HtmlParser/Models/WordsParseResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HtmlParser.Models
{
    public class WordsParseResultsViewModel
    {
        public IDictionary<string, int> WordsRanking { get; set; }
    }
}

HtmlParser/Controllers/HomeController.cs
using HtmlParser.Models;
using HtmlParser.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HtmlParser.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

HtmlParser/Controllers/ParseController.cs
using HtmlParser.Factory;
using HtmlParser.Interfaces;
using HtmlParser.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

namespace HtmlParser.Controllers
{
    public class ParseController : Controller
    {

        private IUtils _utils;

        private readonly ILogger<ParseController> _logger;
        public ParseController(ILogger<ParseController> logger, IUtils utils)
        {
            _logger = logger;
            _utils = utils;
        }
        public IActionResult ImageParse()
        {
            return View();

        }
        public IActionResult ImageParseResults(InputModel model)
        {
              //validate model
           if (ModelState.IsValid)
            {
                ImageParseResultsModel imagesViewModel = new ();

                _logger.LogDebug("Validating the uri informed.");

                if (!Uri.TryCreate(model.Field.Trim(), UriKind.RelativeOrAbsolute, out Uri result))
                {
                    //if it's not possible to create an uri, add errors to the modelstate and returns the initial view 
                    ModelState.AddModelError("Undefined error", $"It was not possible continue the process");
                    return View("ImageParse", model);
                }
                try
                {  
                    //sanitizes the uri
                    result = _utils.GetAbsoluteUri(result);

                    //call the parser factory for a proper instance
                    var parser = new ParserFactory().Create((Enums.ParsingTypes) model.ParsingType);

                    //get the images
                    var imgs = parser.GetImages(result);

                    //give it to the model
                    if (imgs.Any())                        
                        imagesViewModel = new ImageParseResultsModel() { Images = imgs };

                        return View("ImageParseResults", imagesViewModel);

                }
                catch (Exception e)
                {
                    ModelState.AddModelError("Empty Object", $"It was not possible to retrieve images from the informed url: {result.AbsoluteUri}");
                    _logger.LogError($"Message: {e.Message}, Inner message : {e.InnerException}");
                    return View("ImageParse", model);

                }

            }

            return View("ImageParse", model);
        }
        public IActionResult WordsParse()
        {
            return View();
        }
        public IActionResult WordsParseResults(InputModel model)
        {
            if (ModelState.IsValid)
            {
                WordsParseResultsViewModel wordsViewModel = new WordsParseResultsViewModel();

                _logger.LogDebug("Validating the uri informed.");

                if (!Uri.TryCreate(model.Field.Trim(), UriKind.RelativeOrAbsolute, out Uri result))
                {
                    ModelState.AddModelError("Undefined error", $"It was not possible continue the process");
                    return View("WordsParse", model);
                }
                try
                {

                    result = _utils.GetAbsoluteUri(result);
                   
                    var parser = new ParserFactory().Create((Enums.ParsingTypes)model.ParsingType);

                    var  wrds = parser.GetWords(result);
              

                    if (wrds.Any())
                    {
                        //sets the viewmodel and the grafs model , also configures the javascript call for graphs rendering
                        wordsViewModel = new WordsParseResultsViewModel() { WordsRanking = wrds };

                        SetGraphModel(wrds);

                    }

                    return View("WordsParseResults", wordsViewModel);

                }
                catch (Exception ex)
                {  
                    ModelState.AddModelError("Empty Object", $"It was not possible to retrieve data from the informed url: {result.AbsoluteUri}");
                    _logger.LogError($"Message: {ex.Message}, Inner message : {ex.InnerException}");
                    return View("WordsParse", model);
                }

            }

           
            return View("WordsParse", model);

        }

        //Sets graphs model and sets the javascrip call
        private void SetGraphModel(IDictionary<string, int> wrds)
        {
            var data = new ArrayList(wrds.Count());

            var categories = new ArrayList(wrds.Count());

            foreach (var item in wrds)
            {
                categories.Add(item.Key);
                data.Add(item.Value);
            }

            var chartModeData = new { data = data.ToArray(), categories = categories.ToArray() };

            var chartdataJson = JsonSerializer.Serialize(chartModeData);

            ViewBag.JavaScriptFunction = $"RenderGraph({chartdataJson});";
        }
    }
}

HtmlParser/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

    decimal[] SeriesVal = { 50.55M, 55, 41, 17 };
    string[] LabelsVal = { "India", "USA", "UK", "Canada" };


}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HtmlParser/Views/Parse/ImageParse.cshtml
@using HtmlParser.Enums    

@model HtmlParser.Models.InputModel
@{
    ViewBag.Title = "Images Parse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("ImageParseResults", "Parse", FormMethod.Get, new { role = "form" }))
{
    <h5>Inform a website address to list it's images.</h5>
    <hr />
    <div class="form-group">
        <h6>
            @Html.LabelFor(m => m.ParsingType, new { @class = "col-md-2 control-label" })
        </h6>
        <div class="col-md-10">

            @Html.DropDownListFor(m => m.ParsingType, new SelectList(Enum.GetValues(typeof(ParsingTypes))), new { @class = "btn btn-primary dropdown-toggle", @style = "text-align: left;", @onchange = "SelectedIndexChanged()", @id = "ParsingTypeDropDown" })
            <label id="ParsingType" class="alert-info" style="margin-left:3px;"></label>
        </div>
        <hr />
        <h6>
            @Html.LabelFor(m => m.Field, new { @class = "col-md-2 control-label" })
        </h6>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Field, new { @class = "form-control" }) @*
            @type = "url" I have chosen not to set this parameter to allow the user to communicate the name of a site and the solution completes the scheme *@
        </div>

        @Html.ValidationSummary("", new { @class = "text-danger" })

    </div>

    <div class="form-group">
        <div class="col-md" >
            <button type="submit" class="btn btn-primary">Process Images</button>
        </div>
    </div>

}

HtmlParser/Views/Parse/ImageParseResults.cshtml
@model ImageParseResultsModel
@{
    ViewBag.Title = "Images Parse Results";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h5>These are the images we got from the informed site</h5>

<div class="container-xl">

    @foreach (var item in Model.Images)
    {
        @Html.Raw(@item)
    }
</div>

HtmlParser/Views/Parse/WordsParse.cshtml
@using HtmlParser.Enums;
@model HtmlParser.Models.InputModel

@{
    ViewBag.Title = "Words Parse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("WordsParseResults", "Parse", FormMethod.Get, new { role = "form" }))
{
    <h5>Inform a website address to rank it's words.</h5>
    <hr />
    <div class="form-group">
        <h6>
            @Html.LabelFor(m => m.ParsingType, new { @class = "col-md-2 control-label" })
        </h6>
        <div class="col-md-10">

            @Html.DropDownListFor(m => m.ParsingType, new SelectList(Enum.GetValues(typeof(ParsingTypes))), new { @class = "btn btn-primary dropdown-toggle", @style = "text-align: left;" , @onchange = "SelectedIndexChanged()", @id="ParsingTypeDropDown" })
         <label id="ParsingType" class="alert-info" style="margin-left:3px;"></label>
        </div>
        <hr />
        <h6>
            @Html.LabelFor(m => m.Field, new { @class = "col-md-2 control-label" })
        </h6>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Field, new { @class = "form-control" }) @*
        @type = "url" I have chosen not to set this parameter to allow the user to communicate the name of a site and the solution completes the scheme *@
        </div>

        @Html.ValidationSummary("", new { @class = "text-danger" })

    </div>
    <div class="form-group">
        <div class="col-md">
            <button type="submit" class="btn btn-primary">Process Words</button>
        </div>
    </div>

}

HtmlParser/Views/Parse/WordsParseResults.cshtml
@model WordsParseResultsViewModel

@{
    ViewBag.Title = "Words Parse Result";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int i = 1;

}


<h5 style="margin: 32px;text-align: center; font-size: 22px; font-weight: bold; ">Words' Ranking and Graph</h5>

<div class="container-xl" style="display: grid; grid-template-columns: repeat(2,1fr);">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Position
                </th>
                <th>
                    Word
                </th>
                <th>
                    Quantity
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.WordsRanking)
            {
                <tr>
                    <td>
                        @Html.Raw(i++)
                    </td>
                    <td>
                        @Html.Raw(@item.Key)
                    </td>
                    <td>
                        @Html.Raw(@item.Value)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div id="chart" style="min-height: 395px; background-color: #f2f2f2;border: solid; border-style: ridge; "/>
</div>

@if (ViewBag.JavaScriptFunction != null)
{
    <script type="text/javascript">
           @Html.Raw(ViewBag.JavaScriptFunction)
    </script>
    
}

HtmlParser/Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HtmlParser</title>
    <link rel="stylesheet" href="~/css/bootstrap_spacelab.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/apexcharts.css" />

    <script src="~/js/site.js" asp-src-include="true"></script>
    <script src="~/js/apexcharts.min.js" asp-src-include="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HtmlParser</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parse" asp-action="ImageParse">Images Parser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parse" asp-action="WordsParse">Words Parser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HtmlParser - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>